defaults: &defaults
  scrum_master_period: 1
  redmine_url: "http://dev.nuserv.com/issues/"
  deadline_time: 12
  application_url: "localhost:3000"
  campfire_token: 'cbccfeea452bc81fac7021f555471720fb2080dc'
  camfire_room_id : 464963

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  application_url: "standapp.herokuapp.com"