defaults: &defaults
  scrum_master_period: 1
  redmine_url: "http://dev.nuserv.com/issues/"
  deadline_time: 12
  application_url: "localhost:3000"
  campfire_token: '64073638647411f98026fb5895a2ad02aa4b94ac'
  camfire_room_id : 464963

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  application_url: "standapp.herokuapp.com"